import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineComputerDesktop,
  HiOutlineRocketLaunch,
  HiOutlineBadgeCheck,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiWordpress,
  SiHtml5,
  SiCss3,
  SiPython,
  SiC,
  SiMysql,
  SiPostgresql,
  SiMongodb,
  SiElementor,
  SiWoocommerce,
  SiAdobephotoshop,
  SiAdobepremierepro,
  SiAdobelightroom,
  SiCoreldraw,
} from "react-icons/si";

import {
  FaDiscord,
  FaGithub,
  FaLinkedin,
  FaX,
  FaThreads,
  FaInstagram,
  FaXTwitter,
  FaFacebook,
  FaPinterest,
  FaWhatsapp,
  FaReddit,
  FaTelegram,
} from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  wordpress: SiWordpress,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
  html: SiHtml5,
  css: SiCss3,
  c: SiC,
  postgree: SiPostgresql,
  python: SiPython,
  sql: SiMysql,
  mongodb: SiMongodb,
  elementor: SiElementor,
  woocommerce: SiWoocommerce,
  Adobephotoshop: SiAdobephotoshop,
  Adobepremierepro: SiAdobepremierepro,
  Adobelightroom: SiAdobelightroom,
  Coreldraw: SiCoreldraw,
  project: HiOutlineComputerDesktop,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
